apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "charts.backend.fullname" . }}-backend
  namespace: {{ .Values.backend.app.namespace }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "backend.labels" . | nindent 6 }}
  strategy:
    {{- include "weather-app.strategy" . | nindent 4 }}
  template:
    metadata:
      labels:
        {{- include "backend.labels" . | nindent 8 }}
    spec:
      securityContext:
       {{- include "weather-app.securityContext" . | nindent 8 }}
      containers:
        - name: {{ .Values.backend.container.name }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.backend.container.port | default 8000 }}
          securityContext:
              allowPrivilegeEscalation: false
          resources:
            {{- include "weather-app.resources" . | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.backend.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.backend.readinessProbe | nindent 12 }}
          {{- if .Values.backend.startupProbe }}
          startupProbe:
            {{- toYaml .Values.backend.startupProbe | nindent 12 }}
          {{- end }}