apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.service.name }}
  namespace: {{ .Values.backend.app.namespace }}
spec:
   type: {{ .Values.backend.service.type }}
   selector:
     app: {{ .Values.backend.app.name }}
   ports:
     - port: {{ .Values.backend.service.port }}
       targetPort: {{ .Values.backend.service.targetPort }}