apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "charts.frontend.fullname" . }}-frontend
  namespace: {{ .Values.backend.app.namespace }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.frontend.replicaCount | default 1 }}

  selector:
    matchLabels:
      {{- include "frontend.labels" . | nindent 6 }}

  strategy:
    {{- include "weather-app.strategy" . | nindent 4 }}

  template:
    metadata:
      labels:
        {{- include "frontend.labels" . | nindent 8 }}

    spec:


      containers:
        - name: {{ .Values.frontend.container.name }}
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy | default "IfNotPresent" }}

          ports:
            - containerPort: {{ .Values.frontend.container.port | default 8000 }}

          resources:
            {{- include "weather-app.resources" . | nindent 12 }}

          livenessProbe:
            {{- toYaml .Values.frontend.livenessProbe | nindent 12 }}

          readinessProbe:
            {{- toYaml .Values.frontend.readinessProbe | nindent 12 }}

          volumeMounts:
            - name: nginx-cache
              mountPath: /var/cache/nginx

      volumes:
        - name: nginx-cache
          emptyDir: {}