strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: "25%"
    maxSurge: "25%"

hpa:
  name: backendhpa
  namespace: weather-application

frontendHpa:
  name: frontendhpa
  namespace: weather-application 

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000


autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

# Backend specific
backend:
  app:
    name: weather-backend
    namespace: weather-application
    labels:
      app: weather-backend
      env: dev
      tier: backend

  image:
    repository: docdon0007/backend
    tag: "12"
    pullPolicy: IfNotPresent

  container:
    name: weather-backend-container
    port: 8000  # single value (easier)

  service:
    name: weather-backend-service
    type: ClusterIP
    port: 8000
    targetPort: 8000

  livenessProbe:
    httpGet:
      path: /health
      port: 8000
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1

  readinessProbe:
    httpGet:
      path: /health
      port: 8000
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3
    successThreshold: 1

  startupProbe:
    httpGet:
      path: /health
      port: 8000
    initialDelaySeconds: 5
    periodSeconds: 5
    failureThreshold: 10

# Frontend specific
frontend:
  app:
    name: weather-frontend
    namespace: weather-application
    labels:
      app: weather-frontend
      tier: frontend
      env: dev

  image:
    repository: docdon0007/frontend
    tag: "12"
    pullPolicy: IfNotPresent

  container:
    name: weather-frontend-container
    port: 80  # Nginx listens on 80

  service:
    name: weather-frontend-service
    type: NodePort
    port: 80
    targetPort: 80
    nodePort: 30005

  livenessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1

  readinessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3
    successThreshold: 1



ingress:
  name: weather-ingress
  namespace: weather-application 
  className: nginx
  useRegex: "true"

  frontendIngress:
    path: /
    pathType: Prefix
    serviceName: weather-frontend-service 
    servicePort: 80

  backendIngress:
    path: /api(/|$)(.*)
    pathType: ImplementationSpecific
    serviceName: weather-backend-service
    servicePort: 8000