apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ include "weatherapp.frontend.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels: 
    {{- include "weatherapp.frontend.labels" . | nindent 4 }}
spec: 
  strategy: 
    type: {{ .Values.global.strategy.type }}
    rollingUpdate: 
      maxUnavailable: {{ .Values.global.strategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.global.strategy.rollingUpdate.maxSurge }}
  selector: 
    matchLabels: 
      {{- include "weatherapp.frontend.labels" . | nindent 6 }}
  template: 
    metadata: 
      labels:
        {{- include "weatherapp.frontend.labels" . | nindent 8 }}
    spec: 
      containers: 
        - name: {{ .Values.frontend.container.name }}
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          ports: 
            - containerPort: {{ .Values.frontend.container.port }}
          {{- include "weatherapp.frontend.probes" . | nindent 10 }}
          volumeMounts:
            - name: nginx-cache
              mountPath: /var/cache/nginx
      volumes:
        - name: nginx-cache
          emptyDir: {}